name: GPSend
version: '${project.version}'
main: driven.by.data.gpsend.GPSend
api-version: '1.13'
commands:
  gpsend:
    description: Send claim blocks.

depend: [GriefPrevention]
softdepend: [PlaceholderAPI]
