


invalid_type: "&cYou must choose between: PLAYER|ALL"




################################################
# ━━━┳━━━╮
# ┃╭━╮┃╭━╮┃
# ┃┃╱╰┫╰━╯┣━━╮   Version: 2.0.0B
# ┃┃╭━┫╭━━┫━━┫   Author: brihtakai
# ┃╰┻━┃┃╱╱┣━━┃
# ╰━━━┻╯╱╱╰━━╯
################################################

## ERRORS
#no_player: "&cYou need to choose player."
#no_number: "&cYou need to specify how much claim blocks do you want to send."
#no_blocks: "&cYou dont have enought claim blocks!"
#only_int: "&cValue of blocks must be a number!"
#yourself: "&cYou can't send claim blocks to yourself!"
#player_not_found: "&cSorry! We couldn't find that player!"
#usage: "&4Usage: /gpsend <player_name> <number> || /gpsend reload"
#usage2: "&4Usage: /gpsend-all <amount>"
#
## MESSAGES
#reload: "&aPlugin successfully reloaded!"
#no_perm: "&cYou have no permission to do this!"
#only_players: "&cConsole can not execute this command."
#sender: "&aYou send {number} claimblocks to {target}."
#receiver: "&a{player} just sent you {number} claim blocks."
#toall: "&a&l{player} just sent {number} claim blocks to everyone online."
#
#
## Every 24h
#check-for-updates: true