name: GPSend
version: '1.4.3'
main: driven.by.data.gpsend.GPSend
api-version: '1.13'
commands:
  gpsend:
    description: Send claim blocks to player.
  gpsend-all:
    description: Send claim blocks to all online players.

depend: [GriefPrevention]
