name: GPSend
version: '2.0.0'
main: driven.by.data.gpsend.GPSend
api-version: '1.13'
commands:
  gpsend:
    description: Send claim blocks.
  gpsend-admin:
    description: Gpsend admin command.

depend: [GriefPrevention]
